-- CREATE USER TABLE
CREATE TABLE USERS (USERNAME VARCHAR(15) NOT NULL PRIMARY KEY,PASSWORD VARCHAR(32) NOT NULL);

-- CREATE ROLES TABLE
CREATE TABLE ROLES (USERNAME VARCHAR(15) NOT NULL,ROLE_NAME VARCHAR(15) NOT NULL,
                    PRIMARY KEY    (USERNAME, ROLE_NAME),
                    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME));

-- INSERT USERS DATA
-- UNCOMMENT THIS FOR HASHED PASSWORD SUPPORT
-- INSERT INTO USERS VALUES ('sunil', md5('password'));

INSERT INTO USERS VALUES ('kodecamp', 'kodecamp');
INSERT INTO USERS VALUES ('kcamp', 'kcamp');

INSERT INTO ROLES VALUES('kodecamp', 'admin');
INSERT INTO ROLES VALUES('kcamp', 'users');

-- SHOW THE INSERTED RECORDS                                                           
SELECT * FROM USERS LEFT OUTER JOIN ROLES ON USERS.USERNAME = ROLES.USERNAME;
